"""Product names for frozen research Evidence Units; no source is invented."""
EVIDENCE_SOURCES = {
    "REPAYMENT_PERFORMANCE_QUALITY_EVIDENCE": {"internal_id": "REPAYMENT_PERFORMANCE_QUALITY_EVIDENCE", "name": "Repayment history", "category": "Repayment performance", "source": "Historical repayment records", "description": "Recorded payment timeliness and shortfall patterns.", "simulation_source": "Home Credit installments_payments.csv", "cost": "Medium", "privacy": "Medium", "delay": "Medium", "illustrative_cost": 2.0, "illustrative_delay_points": 2.0},
    "BUREAU_ACTIVE_CREDIT_CAPACITY_EVIDENCE": {"internal_id": "BUREAU_ACTIVE_CREDIT_CAPACITY_EVIDENCE", "name": "Active credit obligations", "category": "Credit bureau", "source": "Credit bureau records", "description": "Existing credit exposure and active debt capacity.", "simulation_source": "Home Credit bureau.csv", "cost": "Medium", "privacy": "Medium", "delay": "Instant", "illustrative_cost": 2.0, "illustrative_delay_points": 0.0},
    "BUREAU_CREDIT_HISTORY_QUALITY_EVIDENCE": {"internal_id": "BUREAU_CREDIT_HISTORY_QUALITY_EVIDENCE", "name": "Credit bureau history", "category": "Credit bureau", "source": "Credit bureau records", "description": "History depth, delinquency frequency, and overdue severity.", "simulation_source": "Home Credit bureau.csv and bureau_balance.csv", "cost": "Medium", "privacy": "High", "delay": "Instant", "illustrative_cost": 2.0, "illustrative_delay_points": 0.0},
    "BUREAU_RECENT_CREDIT_ACTIVITY_EVIDENCE": {"internal_id": "BUREAU_RECENT_CREDIT_ACTIVITY_EVIDENCE", "name": "Recent credit activity", "category": "Credit bureau", "source": "Credit bureau records", "description": "Recent credit-account activity before application.", "simulation_source": "Home Credit bureau.csv", "cost": "Low", "privacy": "Medium", "delay": "Instant", "illustrative_cost": 1.0, "illustrative_delay_points": 0.0},
    "REPAYMENT_PRIOR_CREDIT_EXPERIENCE_EVIDENCE": {"internal_id": "REPAYMENT_PRIOR_CREDIT_EXPERIENCE_EVIDENCE", "name": "Previous credit applications", "category": "Prior applications", "source": "Prior application records", "description": "Prior application and approval experience.", "simulation_source": "Home Credit previous_application.csv", "cost": "Low", "privacy": "Medium", "delay": "Short", "illustrative_cost": 1.0, "illustrative_delay_points": 1.0},
}

INITIAL_SOURCE = {"name": "Basic application information", "source": "Applicant intake", "description": "Application, employment, household, and affordability information supplied at intake."}
